### ISSUE TITLE
LOVR v0.16.0 crashes when requiring lovr-mouse

### ISSUE THREAD

**Issue by b0mbie** [bjornbytes/lovr-mouse#6]
After updating to LOVR v0.16.0, I decided to try to use this module, however, when requiring this module, the LOVR window just closes. Here's all of main.lua:
```lua
lovr.mouse = require "lovr-mouse"
```
While trying to figure out what's wrong, I noticed that LOVR closes when [executing this line.](https://github.com/bjornbytes/lovr-mouse/blob/fecd06f2bc844ae89cc8fffc7c28a7f188480263/lovr-mouse.lua#L135)

If `print(window)` is added before this, the console outputs:
```
cdata<struct GLFWwindow *>: NULL
```

**Comment by bjornbytes** [comment]
It's fixed, thanks
